name: CI/CD Task Manager

on:
  push:
    branches:
      - main
      - dev_atividadeAvaliativa

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testes da aplicação
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: task_manager
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d task_manager"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Iniciar aplicação
        run: npm run dev > app.log 2>&1 &
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: task_manager
          DATABASE_USER: admin
          DATABASE_PASSWORD: admin

      - name: Aguardar aplicação iniciar
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000/api/health > /dev/null; then
              echo "Aplicação está disponível!"
              break
            fi

            echo "Aguardando aplicação..."
            sleep 2
          done

      - name: Executar testes
        run: npm test
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: task_manager
          DATABASE_USER: admin
          DATABASE_PASSWORD: admin

  docker:
    name: Build da imagem Docker
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-manager:latest